/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    // {
    //   type: 'category',
    //   label: 'Knowledge Base',
    //   items: [{type: 'autogenerated', dirName: '.'}],
    // },
    { //same as above just shorthand syntax
      'Knowledge Base': [{ type: "autogenerated", dirName: 'knowledge-base' }]
    }
  ],
  docs2: [
    {
      "Tutorials": [{ type: "autogenerated", dirName: 'tutorials' }]
    }
  ],
  teamsOnly: [
    {
      'Teams':
        [
          { type: "autogenerated", dirName: 'teams' },
          // { type: 'ref', id: 'knowledge-base/intro' }, // Document id (string).
        ]
    }
  ]

};
